# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:            Jamin Jiang
tagline:          'Witness Me!'
description:      'Blog of Jamin Jiang. Here are some technical stuff. Some notes about development.'
url:              http://JaminJiang.github.io

author:
  name:           'Jamin Jiang'
  url:            http://JaminJiang.github.io
  gravatar:       https://en.gravatar.com/jaminjiang
  photo:          https://avatars0.githubusercontent.com/u/8405915?v=3&s=460
  introduction:   'I am a postgraduate student and pursuing for master degree. You may include HTML <a href="#">here</a>.'

paginate:         5
paginate_path:    '/blog/page:num'

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/JaminJiang/JaminJiang.github.io
